name: Java CI

on: 
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -f complete --batch-mode --update-snapshots verify